name: MCWarfare
main: com.orange451.mcwarfare.MCWarfare
version: 1.0
website: http://multiplayerservers.com/
author: orange451
softdepend: [PVPGunPlus, TagAPI]
commands: 
  war:
    description:
    usage:
  giveperk:
    description:
    usage:
  givegun:
    description:
    usage:
  givekillstreak:
    description:
    usage:
  giveclass:
    description:
    usage:
  givexp:
    description:
    usage:
  profile:
    description:
    usage:
  permission:
    description:
    usage:
  ver:
    description:
    usage:
  version:
    description:
    usage:
  ?:
    description:
    usage:
  stop:
    description:
    usage: